#cc_binary(
#    name = "main",
#    srcs = [
#        "main.cpp",
#    ],
#    deps = [
#        "@org_tensorflow//tensorflow/cc:cc_ops",
#        "@org_tensorflow//tensorflow/cc:client_session",
#        "@org_tensorflow//tensorflow/core:tensorflow",
#        "@org_tensorflow//tensorflow/core:framework",
#    ],
#)
