game_conf: {
    board_size: 13
    win_num: 5
}

model_conf: {
    model_path: "/Users/admin/fish/code/AlphaZero-Renju/cpp/model"
    residual_blocks: 3
    batch_size: 10
    l2_c: 0.00001
    lr: 0.001
    train_model_weight_save_path: "/Users/admin/fish/code/AlphaZero-Renju/cpp/weights/train"
    predict_model_weight_save_path: "/Users/admin/fish/code/AlphaZero-Renju/cpp/weights/predict"
    load_pre: true
}

self_play_conf {
    data_pool_size: 10000
    producer_threads_num: 7
    producer_log_freq: 10
    examiner_threads_num: 7
    examiner_game_num: 14
    examiner_interval: 30
    train_step_interval: 200
    trainer_log_freq: 100
}

mtcs_conf: {
    simulate_num: 1000
    c_puct: 5
    explore_steps: 4
    dirichlet_esp: 0.25
    dirichlet_alpha: 1.0
}

data_conf: {
    init_game_num: 200
    batch_game_num: 20
    data_path: "data.pkl"
}

ui_conf: {
    background_size: 630
    game_area: 540
    background: "images/small.jpg"
}
