game_conf: {
    board_size: 10
    win_num: 5
}

model_conf: {
    #model_path: "/home/liuyekuan/workspace/mine/AlphaZero-Renju/cpp/model"
    #model_path: "/Users/admin/repos/AlphaZero-Renju/cpp/model"
    model_path: "/home/ubuntu/AlphaZero-Renju/cpp/model"
    residual_blocks: 2
    batch_size: 4
    save_every_n_games: 100
    l2_c: 0.00001
    lr: 0.01
    validation_split: 0.2
}

mtcs_conf: {
    simulate_num: 100
    c_puct: 5
    explore_steps: 4
    dirichlet_esp: 0.25
    dirichlet_alpha: 1.0
}

data_conf: {
    init_game_num: 200
    batch_game_num: 20
    data_path: "data.pkl"
}

ui_conf: {
    background_size: 630
    game_area: 540
    background: "images/small.jpg"
}